name = "VerdantAges"
author = "Lacey-Anne Sanderson (MossbornHedgehog)"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2accc28cd94ca4684f8b1071d28cecedf761069b7e09d871c895f0287d4aecd"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
