name = "VerdantAges"
author = "Lacey-Anne Sanderson (MossbornHedgehog)"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e8b9c27c26e40c5fd48b0c905bbd3aa76e725047f3d57c74b4dc7bac59c63db"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
